version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    logging:
      options:
        max-size: 10m
        max-file: "3"

    ports:
      - '5432:5432'
    volumes:
      - ./database:/var/lib/postgres
